version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: reservation
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
